### ISSUE TITLE
Travis OSX build is failing...

### ISSUE THREAD

**Issue by luzpaz** [nitramr/scribus-indigo#17]
because it's exceeding the maximum compile time for travis. So I think we should remove OSG from both Linux and OSX because it's taking time to download it and both of the builds are throwing a lot of warnings. I'll open an PR soon to do this.

**Comment by nitramr** [comment]
Fixed

**Comment by luzpaz** [comment]
Build still fails on some attempts (https://travis-ci.org/nitramr/scribus-indigo/jobs/176443094)
Investigate why....
